services:
  - type: web
    name: reginox-clone
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_BUCKET_ID
        sync: false
